packages:
  - "artifacts/*"
  - "lib/*"
  - "lib/integrations/*"
  - "scripts"

onlyBuiltDependencies:
  - "@whiskeysockets/baileys"
  - bcrypt
  - esbuild
  - msgpackr-extract
  - protobufjs
  - sharp
